### ISSUE TITLE
Modules don’t mirror the toggles in settings.

### ISSUE THREAD

**Issue by GTO683** [AzzouDuGhetto/Coeus#2]
Fortunately you can enable and disable what you desire via the module however, if you manually toggle (activate/deactivate) the setting that is associated with the module in settings, the toggle doesn't match that. Example: I enabled Location services via my custom Coeus module, however if I go into settings and manually disable Location Services, my custom module remains highlighted as if location services is still on. Ideally, disabling Location services via the toggle in settings would unhighlight my module, so they match.

**Comment by AzzouQ** [comment]
That's a well known issue, I've started to re-write that part (In fact i was planning on releasing a whole knew CoeusReloaded with lots of extra features), and instead of Activator, use the native iOS methods, like this, change will be modified live, just like the Connectivity Module does. Sadly, I can't jailbreak atm, may takes time until I start working on it again.

**Comment by AzzouQ** [comment]
I'll close this issue as Coeus is not maintained anymore in favor of CoeusReloaded (temp name lol), will try to integrate that when it will be released 😁
